### ISSUE TITLE
Only inject string values, any other type throws errors

### ISSUE THREAD

**Issue by VitorLuizC** [giowe/gulp-sass-vars#1]
IDK if it's by design, but I can't inject numbers, booleans or Objects.

![2016-12-28 11_07_15-cmder](https://cloud.githubusercontent.com/assets/9027363/21522577/e9e5a0c4-cced-11e6-92c7-d319ed71ec56.png)

```js
// gulpfile.js
const gulp = require("gulp");
const sass = require("gulp-sass");
const vars = require("gulp-sass-vars");

const settings = {
  url: {
    base: "http://localhost:8080/",
    img: {
      avatar: "http://localhost:8080/img/avatar.svg"
    }
  }
};

gulp.task("style:transpile", transpileStyle);

function transpileStyle() {
  gulp.src("./style.scss")
    .pipe(vars(settings))
    .pipe(sass())
    .pipe(gulp.dest("./"));
}
```

```scss
// style.scss
@function image($alias) {
  $images: map-get($url, 'img');

  @return url('#{map-get($images, $alias)}');
}

.avatar {
  background-image: image(avatar);
}
```

> I've fixed this locally and will be glad to make a pull-request :smile:
