### ISSUE TITLE
Extra quotes around fonts?

### ISSUE THREAD

**Issue by Anahkiasen** [giowe/gulp-sass-vars#7]
If I try to inject per example `'font-family': 'Garamond, serif'` it gets injected as `$font-family: "Garamond, serif";` which the browser then interprets as one font. Not sure how this could be worked around, is there an option to pass maybe so that `parse-sass-value` doesn't autoquote things? I wouldn't mind having to quote things myself.

**Comment by VitorLuizC** [comment]
You could also use an `Array` to define those font-families. 
```js
// ...
{ 'font-family': [ 'Garamond', 'serif' ] }
```
`Array` will be parsed as `SASSList` which is a valid font-family value.
```scss
$font-family: ('Garamond', 'serif');

.text {
  font-family: $font-family;
}
```
